### ISSUE TITLE
Actions need a way to express time stamps

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#101]
See #100

**Comment by benfrancis** [comment]
I assume a timestamp would be added as a member of the [ActionStatus](https://w3c.github.io/wot-profile/#ActionStatus) object. But what should the timestamp be for? The time at which an action was requested, or the time at which the action was completed? What should these member(s) be called?

As a data point, WebThings [currently provides](https://webthings.io/api/#action-resource) both `timeRequested` and `timeCompleted` for each action in the action queue.

**Comment by mlagally** [comment]
I think we should include both time stamps, the proposed names are fine with me.
There's however a few problems with timestamps:
1. the device needs a clock, not sure we can require sensors to have that
2. the clock must have been set and should run accurately
3. there's clock skew in a group of devices, times are "floating"
One way to resolve the accuracy problem is to pass in the request time in the action request and define fallback values for devices without a clock. This works well for actions but not for events.

Probably the best approach to address the accuracy problem is to store the action request / subscription time and use relative times to return the timeCompleted / time when the event occurred.

**Comment by benfrancis** [comment]
@mlagally I think for an HTTP binding we have to assume that the device has a clock. There are multiple places in the HTTP protocol itself which require timestamps, such as the `Date`, `Last-Modified`, `Expires` and `Retry-After` headers. That doesn't necessarily mean that the physical device itself has to have a clock, but the hardware which is providing its HTTP API (which may be a gateway or a cloud service for example) does.

It is certainly true that clocks are not always correctly set and don't keep perfect time. The Raspberry Pi for example doesn't have a Real Time Clock and needs its time setting from an NTP server on the internet on every boot. Without an internet connection (or some other time source like an external RTC or GPS module) this could result in quite a few timestamps which appear to be from the 1970s!

I don't think using a timestamp from the invoke action request from the Consumer + a relative action duration necessarily solves the problem, since the clock on the Consumer could be wrong too.

I'd suggest that if a Consumer can't trust that timestamps on an Action were generated using the correct time, then the best they can do is to treat timestamps from a given device as relative to each other, rather than relative to the actual current time.

We could add a note to the specification to that effect, as an implementation warning.

**Comment by benfrancis** [comment]
> I think we should include both time stamps, the proposed names are fine with me.

OK, happy to do that. One thing this doesn't cover is whether there should be a timestamp for the `failed` state too, e.g. `timeFailed`. A timestamp called `timeCompleted` with a status of `failed` might cause confusion.

**Comment by benfrancis** [comment]
The PR I have submitted (#101) adds `timeRequested`, `timeCompleted` and `timeFailed` members to the ActionStatus object. These are all optional, which also helps with the issue identified by @mlagally regarding devices that don't have clocks. (This is also true of the [proposed solution for events](https://github.com/w3c/wot-profile/pull/119), where it's RECOMMENDED but not mandatory that timestamps be used as event IDs. In that case devices that don't have a clock could just use an incrementing integer instead for example).

**Comment by mlagally** [comment]
I think having all of these optional causes confusion and does not help interoperability.
It mixes time stamps and status indications. (succeeeded, failed).
You could have contents in both members, which is not logical.
For this case the profile has to define exclusion rules, which complicaties the spec.
