### ISSUE TITLE
Events - Scalable event mechanism for cloud use cases

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#107]
The current event mechanism in the core profile relies on SSE.

Whereas this is completely appropriate for deployments, where only a few devices are managed by a clonsumer, this mechanism does not scale well to scenarios, where hundreds or thousands of devices are sending events to a common consumer.

The SSE mechanism is basically a "poll" with an open connection. For devices with a low rate of event notifications, this is not appropriate, since it consumes network resources without significant traffic.

We need a second "push" based mechanism that can be used in deployment scenarios of hundreds or thousands of devices.
Webhooks are a natural choice for device initiated event notifications.
The TD specification already contains a Webhook example: https://w3c.github.io/wot-thing-description/#webhook-example-serialization

The profile specification has to define a corresponding section.

**Comment by benfrancis** [comment]
> this mechanism does not scale well to scenarios, where hundreds or thousands of devices are sending events to a common consumer.

There are certainly more efficient ways of pushing events over a network (like UDP multicasting), but not necessarily over HTTP (the protocol used by the Core Profile).

> The SSE mechanism is basically a "poll" with an open connection.

That's not how I'd describe it. it's a push mechanism over a TCP socket. It's a special type of HTTP request which the server knows to keep open, as opposed to long-poll where it has to be re-opened every time a message is pushed to the client. In this respect it's similar to WebSockets except that it's unidirectional, limited to UTF-8 encoded messages, has some limited built-in semantics for describing events, and its own dedicated JavaScript API in web browsers.

> We need a second "push" based mechanism that can be used in deployment scenarios of hundreds or thousands of devices.
> Webhooks are a natural choice for device initiated event notifications.

I disagree.

Firstly, do you have evidence that webhooks would be any more efficient? Have you tested it? Webhooks would require keeping fewer TCP sockets open, but those may be relatively cheap compared with needing to send a whole new HTTP request for every event emitted.

Secondly, webhooks require that the consumer is a web server which is not always (I'd say usually not) the case. What if the consumer is a local desktop or mobile app for example?

> The profile specification has to define a corresponding section.

Is that a resolution, or your opinion?

**Comment by egekorkan** [comment]
+1 to all the points above by @benfrancis

**Comment by mlagally** [comment]
The fundamental problem in these "poll"-based event mechanism - or should we say "consumer initiated" mechanisms is that they don't match to scenarios behind a firewall. 

Wrt. server deployment scenarios:
It is quite common for cloud and edge deployments to establish a server endpoint, so a webhook is a natural choice, see also the commercial examples in the vF2F presentation.

For mobile deployments where traffic cost still plays a role, it is also not ideal to keep a connection open for a long time without any real message traffic. TCP/IP has some management traffic to keep a connection open, so an event mechanism, where network traffic only occurs when there's actual (event) messages to be transmitted, has lower cost.

There are some problems with changing IP addresses on mobile networks (e.g. roaming scenarios), but these can be addressed by dynamic DNS.

**Comment by benfrancis** [comment]
@mlagally wrote:
> The fundamental problem in these "poll"-based event mechanism - or should we say "consumer initiated" mechanisms is that they don't match to scenarios behind a firewall.

I don't understand what you mean. If a consumer can't send a `GET` request to subscribe to an event then it can't send a `PUT` request to write a property or a `POST` request to invoke an action either. It is a fundamental assumption of the Core Profile that a conforming Thing is an HTTP server and the Consumer is an HTTP client which can reach it. I agree there can be problems with making a web server behind a firewall reachable from the internet (DNS, TLS, NAT etc.), but those problems are common to the whole HTTP protocol binding, not just events [1][2].

> Wrt. server deployment scenarios:
> It is quite common for cloud and edge deployments to establish a server endpoint, so a webhook is a natural choice, see also the commercial examples in the vF2F presentation.

It is certainly possible that a Consumer conforming to the Core Profile is a web server in addition to being a web client, but that can't be assumed to be true for all conforming Consumers.

> For mobile deployments where traffic cost still plays a role, it is also not ideal to keep a connection open for a long time without any real message traffic. TCP/IP has some management traffic to keep a connection open, so an event mechanism, where network traffic only occurs when there's actual (event) messages to be transmitted, has lower cost.

That's a bit of a simplistic view. Either you keep one TCP socket open on each device for the lifetime of a subscription, or you open a new TCP socket on the consumer for every event emitted. If an event is emitted even just once a second from 100 devices the consumer is now dealing with 100 HTTP requests per second and you've DDoS'd your own server.

> There are some problems with changing IP addresses on mobile networks (e.g. roaming scenarios), but these can be addressed by dynamic DNS.

I'm not sure if you're talking about the Consumer or the Thing, but this is true either way.

---- 

Footnotes:
1. We already solved all these problems in WebThings with a dynamic tunnelled reverse proxy service. It's not ideal, but if you want Things to be web servers as in the Core Profile, these are the kinds of problems you have to solve.
2. I do actually agree that there's a case for a protocol binding which can work the other way around (e.g. where the Thing is the client and the Consumer is the server), but that would have to be a whole separate protocol binding since it turns the whole thing on its head. It could actually be fairly straightforward for a [WebSocket sub-protocol](https://w3c.github.io/web-thing-protocol/requirements/#websocket-sub-protocol) to work in both directions.

**Comment by egekorkan** [comment]
Regarding what @mlagally wrote on:

> It is quite common for cloud and edge deployments to establish a server endpoint, so a webhook is a natural choice, see also the commercial examples in the vF2F presentation.

I have checked the presentations:
- Echonet: No mention of eventing
- Takenaka: Webhook can be seen for cold data in slide 19. 
- Hitachi: No mention of eventing (mostly about discovery)
- NHK: No mention of eventing details in the emulator


Also, zero Things with Webhook in Plugfests. Webhook is not a simple mechanism and needs experimentation on how it works with TDs. The webhook example in the TD spec raises a lot of confusion and is not understandable in general.

Notes:
1. I am not saying that Webhooks is an unused technology. It has its uses and would be a technology I would consider if I was implementing a new IoT platform.
2. I could have missed mentions of Webhooks being used in commercial examples in VF2F presentations.
3. I am against specifying untested _stuff_. Given that we will have no plugfest until the next charter, I am against introducing such mechanisms. When there was zero profile using TDs or Things in the plugfest, introducing such new mechanisms is not wise. 
4. At this point, I am more and more thinking of saying that this profile should be called HTTP Cloud Profile if such requirements are **driving** the specification.

**Comment by benfrancis** [comment]
@egekorkan wrote:
> 2. I could have missed mentions of Webhooks being used in commercial examples in VF2F presentations.

@mlagally may be referring to the list of Webhooks use cases in non-IoT contexts in https://github.com/w3c/wot/blob/main/PRESENTATIONS/2021-10-online-f2f/2021-10-27-WoT-F2F-Architecture%2BProfiles-Lagally.pdf (such as GitHub, PayPayl, Atlassian and Wordpress).

Let me put this another way. @mlagally Is it your intention that in adding webhooks as an eventing mechanism for the Core Profile, all consumers conforming to the Core Profile must be both an HTTP client and an HTTP server?

**Comment by benfrancis** [comment]
See also: #108

**Comment by mlagally** [comment]
@egekorkan many thanks for doing this due diligence and checking the presentations from the vF2F.
@benfrancis, you are right, I spoke about the WebHook examples from the Profile presentation.

I also did a brief check of TDs of the recent plugfest - there's quite a variety of event mechanisms being used, so it will be difficult to pick a single mechanism.

**Comment by mlagally** [comment]
I think we can close this issue.

**Comment by benfrancis** [comment]
@mlagally wrote:
>  also did a brief check of TDs of the recent plugfest - there's quite a variety of event mechanisms being used

This is not a surprise, since there are many options available and there's currently no recommended default choice.

WebThings didn't use Server-Sent Events either, until we agreed on that as the event mechanism for the Core Profile protocol binding.

> We could consider removing the events mechanism from the core profile at this point

How would that improve the situation?

We need to define a protocol binding for events as part of the Core Profile. Server-Sent Events is the mechanism we agreed on based on our collective implementation experience, and the SSE-based events protocol binding we've defined already has at least two implementations that I'm aware of.

We all know SSE has limitations (as do all the other HTTP-based event mechanisms). If you have an alternative proposal for an HTTP-based event mechanism which would better fit the requirements of the Core Profile, with implementation experience to prove it, then of course we can re-visit that decision.

**Comment by egekorkan** [comment]
Answering https://github.com/w3c/wot-profile/issues/134#issuecomment-981431123 regarding the use of SSE or Webhook.

I don't think that it makes sense to force Things and Consumers to be server and client at the same time. If we have properties accessible over basic HTTP requests where the Thing is a server and Consumer is a client, why for events the Thing suddenly becomes a client and Consumer a server?

Also regarding @mlagally's specific point about:
> Please don't think of browsers as the only consumers 

I do not think that but the current profile (and ANY profile that will come in the future) has the very basic concept: All consumers must implement all the features of the profile. If one type of consumer does not implement one part of the profile, we cannot achieve the interoperability claims.

If we choose the browser as one of the Consumers (not all the Consumers but **just** one), it will not be able to implement webhooks and simply is not a profile compliant consumer. Thus, going in the webhooks direction will simply exclude **all** browsers from being Consumers of an HTTP profile. If this outcome is desirable, I would not oppose Webhooks.

**Comment by benfrancis** [comment]
Following up on the discussion from the WoT Profile meeting on 2022-03-02 (which I wasn't able to participate in due to a calendar conflict).

Four alternatives were proposed for the the event model in WoT Profile.

> 1. completely remove events from core profile

This means no interoperability.

> 2. define 3 variants of core profile: core+SSE, core+longpoll, core+webhook

This works against interoperability since there are now three core profiles, causing fragmentation.

> 3. include 3 event mechanisms in core profile, make event support optional for consumers

Making event support optional for consumers breaks the requirement that a Consumer should be able to interact with all affordances of a Thing. Therefore if there are three event mechanisms which could be used by Things within a single profile, then either all Things or all Consumers have to implement all three mechanisms. That makes implementation very complicated and in some cases impossible (with the given examples).

> 4. mandate a single event model to be supported by all consumers

This is the only option which guarantees out-of-the box interoperability. However, it's only necessary to mandate a single event model _per profile_ and we have established that profiles are composable.

First, I propose some general principles:
1. We agree that in general a Thing or Consumer _could_ be an HTTP client, an HTTP server, or both
2. The Core Profile shouldn't _require_ that any Thing or Consumer be both an HTTP client and an HTTP server because that is complicated (and in some cases impossible) to implement
3. Each profile should ideally use only define a single protocol binding for each operation, to simplify implementation and guarantee interoperability

This issue was triggered by @mlagally use case of a Thing which acts as a web client to push events to a Consumer which acts as a web server, using webhooks. A can't think of an obvious way that a Thing acting only as a web client can have its properties set and actions invoked.

Therefore I propose defining a separate profile (Webhooks Profile? Event Push Profile?) which defines a protocol binding for subscribing to events using webhooks, and nothing else, specifically to fulfil that deployment model and use case. That profile can then be composed with other profiles (e.g. the Core Profile, or another) in order to provide protocol bindings for properties and actions.

**Comment by benfrancis** [comment]
I've been thinking more about this following the group discussion on my proposal in today's WoT Profile call.

What I originally had in mind was two profiles, let's call them the **HTTP Client-Server Profile** and the **HTTP Server-Client Profile**. The former assumes the Consumer is an HTTP client and the Thing is an HTTP server, and the latter assumes the Consumer is an HTTP server and the Thing is an HTTP client.

**HTTP Client-Server Profile**
- read/write properties - HTTP GET and PUT
- observe/unobserve properties - HTTP GET (Server-Sent Events)
- invoke/query/cancel actions - HTTP POST, GET and DELETE
- subscribe/unsubscribe events - HTTP GET (Server-Sent Events)

**HTTP Server-Client Profile**
- subscribe/unsubscribe events - Webhooks
- observe/unobserve properties - Webhooks

Since I couldn't think of an obvious way to read/write properties and invoke/query/cancel actions where the Thing is only an HTTP client, I proposed that the latter profile only define an event mechanism, and make use of composition with other profiles for the other affordances.

However, I think it would be helpful to establish a shared understanding of what we actually mean when we say "webhooks". As I understand it there is no webhooks standard, it's more of a design pattern*. The basic convention is that there's a provider which sends an HTTP POST request to a consumer via callback URL and the payload is usually JSON. Beyond that there's very little convention. There's no standard mechanism for installing a webhook (i.e. subscribing to an event) for example. My idea of the **HTTP Server-Client Profile** profile was therefore limited to the actual emitting of events. However, reflecting on the group discussion I realise that that's not the full picture, since a Consumer also needs to be able to subscribe/unsubscribe from events as well as just receiving them.

I suspect this is where @mlagally is talking about both the Thing and Consumer being "Servients", since both would need to be an HTTP client and an HTTP server? The Consumer acts as a client to subscribe and a server to receive events, and the Thing acts as a client to push events and a server to listen for subscriptions. If the **HTTP Server-Client profile** covered a mechanism whereby a Consumer could install a webhook on a Thing (i.e. subscribe/unsubscribe to an event) using an HTTP POST request in the other direction, then it might be more accurate to describe that profile as the **HTTP Servient-Servient Profile**. That means that all Things and Consumers would have to be both an HTTP client and an HTTP server. I said above that the Core Profile (**HTTP Client-Server Profile**) shouldn't require that any Thing or Consumer be both an HTTP client and HTTP server, but if that's how the webhooks protocol binding works then that would have to be the case for the **HTTP Servient-Servient Profile**.

If the event model of the **HTTP Servient-Servient Profile** requires that all Things and Consumers be both HTTP clients and servers, then maybe it would in fact be appropriate for that profile to re-use the same protocol bindings for other operations with the HTTP Client-Server profile. E.g.

**HTTP Servient-Servient Profile**
- read/write properties - HTTP GET and PUT
- observe/unobserve properties - HTTP POST (Webhooks)
- invoke/query/cancel actions - HTTP POST, GET and DELETE
- subscribe/unsubscribe events - HTTP POST (Webhooks)

This is essentially the core+webhook profile from the second proposed alternative above, just with a different name. As long as we also have the **HTTP Client-Server Profile** (i.e. the core+see proposal above) where a Consumer doesn't also have to be a web server, then I think I could support that:

1. **HTTP Client-Server Profile** - most appropriate for multiple Consumers listening for high frequency events from a single Thing
2. **HTTP Servient-Servient Profile** - most appropriate for single Consumer listening to low frequency events from a large number of Things

It should be fine to do this within the current charter since the charter allows for multiple profiles, and it might not actually be that much additional work since we can essential duplicate (or reference) the existing property and action protocol binding for both profiles.

What does everyone else think?

Note that neither of these REST-like event models scales particularly well in the case where there's a single Consumer listening to high frequency events from a large number of Things. We may eventually want to define a separate profile for that using a different deployment model (e.g. using an intermediary hub and/or a different protocol).

---

\* [WebSub](https://www.w3.org/TR/websub) is a W3C recommendation based on webhooks, but it has a more complex [deployment model](https://www.w3.org/TR/websub/#high-level-protocol-flow) involving publishers, subscribers and hubs. I'm not sure how appropriate that is to the use case @mlagally had in mind.

**Comment by egekorkan** [comment]
Just some further points that might help to understand some visions regarding actions and properties in mind. I will firstly not use the words consumer, thing, client, or server. I remember reading this either in Azure or AWS IoT documentation but I could not find the resource right now.

1. The Thing sends regularly HTTP POST requests with some data (generally telemetry and event data).  This is eventing when mapped to WoT.
2. The response to that request can contain some commands, like change update interval, sleep, move to another location (exaggerating a bit). This is actions when mapped to WoT.
3. (my interpretation) The response can have some other types of commands to send a sensor value right now instead of waiting for the next event emission time. This is properties when mapped to WoT.

Thus, it is still possible to do actions and properties in an HTTP Server-Client profile. However, this is a big paradigm change for us as the WG with zero experience from plugfests. We do not even know how a TD of such a Thing can look like. I would propose that such new areas should not be rushed and postponed to the next charter with a specific set of people who work on this.

**Comment by benfrancis** [comment]
@egekorkan Interesting, but how on earth would you describe those property and action affordances using a Form in a Thing Description? The URL associated with those operations would be different for every Consumer and the payload of property and action operations is contained in a response to the sending of an event rather than initiated as an HTTP request by the Consumer. If we do end up constraining profiles to what is possible through declarative protocol bindings in Thing Descriptions, I don't think this would be covered by the current HTTP protocol binding template.

I agree with you that whilst technically possible, this approach seems to go well beyond the implementation experience of the Working Group so far (that I'm aware of).

What's your view on how we should accommodate the HTTP client sensor use case given the latest discussion? Do you think an HTTP Servient-Servient profile which combines webhooks with the Client-Server protocol bindings for properties and actions makes sense?

**Comment by benfrancis** [comment]
@mlagally So that we can move beyond theoretical discussions, do you have an example implementation of your sensor+cloud use case we can use as a proof of concept to generate Thing Descriptions for for plugfests? Or an intention for Oracle to implement one within the timeframe of this charter? It sounds like implementation experience would really help here.

We're going to need at least two implementations of each profile after all.

**Comment by benfrancis** [comment]
In today's WoT Profile call, @mlagally shared some [slides](https://github.com/w3c/wot-profile/blob/afd2211abc23dac6a99618c763f6415b9f37b032/contributions/2022-3-23-WoT-Profiles-Eventing.pdf) with a proposal for:
- A baseline HTTP profile
- Multiple alternative protocol bindings outside of that profile (extension profiles?) for observable properties and events
    - SSE
    - WebSocket
    - Longpoll
    - Webhooks*

\* The presentation didn't include Webhooks, but I assume from previous conversations that @mlagally would like a binding for that too.

I noted on the call that my concern with this proposal is the risk of fragmentation (the opposite of what we are trying to achieve with profiles) if Producers and Consumers can choose from lots of different event mechanisms. It either means that to guarantee out-of-the-box interoperability _all_ conformant Producers and Consumers would have to implement _all_ of the event bindings, or we accept that for implementations which use events out-of-the-box interoperability can only be guaranteed if a given Producer and Consumer share the same event mechanism in addition to implementing the baseline HTTP profile.

However, I also agree that SEE is not a good fit for all deployment scenarios (e.g. a large number of sensors pushing readings to a centralised cloud service, as per @mlagally's example) and that in some cases alternative mechanisms may be more appropriate.

@mmccool pointed out that in many ways @mlagally's proposal and my proposal in https://github.com/w3c/wot-profile/issues/107#issuecomment-1063073402 are not actually that different and that perhaps we are close to a solution.

Therefore, as a compromise how about we adopt @mlagally's proposal and for WoT Profile 1.0 we define...

---

**HTTP Baseline Profile**
- `readproperty`
- `writeproperty`
- `readallproperties`
- `writemultipleproperties`
- `invokeaction`
- `queryaction`
- `cancelaction`
- `queryallactions`

**HTTP SSE Profile**
- `subscribeevent`
- `unsubscribeevent`
- `subscribeallevents`
- `unsubscribeallevents`
- `observeproperty`
- `unobserveproperty`
- `observeallproperties`
- `unobserveallproperties`

**HTTP Webhooks Profile**
- `subscribeevent`
- `unsubscribeevent`
- `subscribeallevents`
- `unsubscribeallevents`
- `observeproperty` (if possible)
- `unobserveproperty` (if possible)
- `observeallproperties` (if possible)
- `unobserveallproperties` (if possible)

--- 

The HTTP SSE Profile and HTTP Webhooks Profile are clearly differentiated:
- HTTP SSE Profile
  - Producer is a server and the Consumer is a client
  - Works best for multiple Consumers listening for high frequency events from a single Producer
- HTTP Webhooks Profile
  - Producer is a servient and Consumer is a servient
  - Works best for a single Consumer listening to low frequency events from multiple Producers

Things could implement the HTTP Baseline Profile in addition to one, both or none of the HTTP SSE Profile and HTTP Webhooks Profile. In order to enable out-of-the-box interoperability a Consumer would need to support all the profiles implemented by a given Producer.

For now I don't think anyone is asking for a profile which mandates long-polling and I can't think of greenfield scenarios where there are advantages of using that over SSE, but if there is a demand for that then we could discuss it.

I think WebSockets is different to all of the other event mechanisms in that it's a bi-directional synchronous communications channel and therefore not limited to just events. I am interested in working on a WebSockets Profile (perhaps in the next version of the WoT Profile specification if we can't get it done in this charter period?) which covers all of the operation types (including properties, actions and events) using the [Web Thing Protocol](https://www.w3.org/community/web-thing-protocol/) as a WebSocket sub-protocol, and allows for multiple types of operations (and even multiple Things) over a single connection.

What does everyone think?

**Comment by benfrancis** [comment]
I've submitted PR #188 so we can see what splitting the current Core Profile into an HTTP Baseline Profile and HTTP SSE Profile might look like.

**Comment by mlagally** [comment]
Thanks very much @benfrancis for working out the proposal in #188. I'm sure this resolves our previous contention and moves us significantly forward towards the completion of the spec.

**Comment by mlagally** [comment]
I also think the new names are clarifying some previous confusions.

**Comment by danielpeintner** [comment]
I have no solution to the _root_ problem. I would only like to mention that it does not seem to be target-oriented to have a longer list of different profiles at the end. The consequence would be again no interoperability ... except for properties.

**Comment by benfrancis** [comment]
@danielpeintner wrote:
> I have no solution to the _root_ problem. I would only like to mention that it does not seem to be target-oriented to have a longer list of different profiles at the end. The consequence would be again no interoperability ... except for properties

I agree, and I would much prefer there to be a single HTTP profile which works for the 90% of use cases where the Thing is a server and the Consumer is a client. For the other 10% we could suggest using other protocols (e.g. MQTT) on the back end and bridging to the HTTP profile using a gateway.

However, we appear to be at an impasse where we can not move forward with the WoT Profile specification unless @mlagally is satisfied that we can fulfil the requirements of two very different deployment models (described above). I can't think of a practical solution to satisfying those two deployment models except by defining two separate profiles.

**Comment by mlagally** [comment]
A scalable event mechanism has been described in the WebHook profile, suggest we close the issue.
