### ISSUE TITLE
Is HTTP Baseline required for HTTP Webhooks or SSE?

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#228]
Webhook profile says:

> The HTTP Webhook profile MAY be used in conjunction with the [HTTP Baseline Profile](https://w3c.github.io/wot-profile/#http-baseline-profile) in order to provide operations to read and write properties and invoke, query and cancel actions.

There are two problems with this:

- [ ] There is no equivalent sentence for the SSE profile
- [ ] It is not clear if I can use the Webhook profile on its own, i.e. without the baseline profile. My guess is that it is not the case but the text is not clear about that

**Comment by benfrancis** [comment]
I agree with @mlagally that Consumers (and Things) should not be required to implement the HTTP Baseline Profile in order to support the HTTP SSE Profile or HTTP Webhook Profile.

This is currently a bit confusing because the Baseline Information Model inside the HTTP Baseline Profile contains [constraints](https://w3c.github.io/wot-profile/#x5-event-affordance) on event affordances, whereas the HTTP SSE Profile and HTTP Webhook Profile do not. My suggested solution to this is to remove the constraints altogether.

> A Thing MAY define more than one event mechanism to enable a variety of consumers.

This assertion doesn't really have any effect since this is already true for any Thing.

> The Array of Form of each event MUST contain only a single endpoint. 

This assertion contradicts the first assertion.

> uriVariables MUST NOT be used. 

This is also probably unnecessary since the profiles defines the protocol bindings, any uriVariables which aren't used by that protocol binding would be ignored.

**Comment by danielpeintner** [comment]
> I agree with @mlagally that Consumers (and Things) should not be required to implement the HTTP Baseline Profile in order to support the HTTP SSE Profile or HTTP Webhook Profile.

I don't wanna restart the "naming" discussion but the term "baseline" to me indicates the _basis_ of all the other profiles

**Comment by benfrancis** [comment]
> I don't wanna restart the "naming" discussion but the term "baseline" to me indicates the _basis_ of all the other profiles

I agree the naming is still a bit confusing. Ideally I would prefer there was just a single "HTTP Profile" with a single event mechanism, but we were not able to agree on one.

The structure of the specification is still a bit fluid (see #214), but if the HTTP Baseline Profile ends up defining constraints which are also intended to apply to the HTTP SSE Profile and HTTP Webhook Profile (e.g. data model constraints, links, security schemes, discovery mechanisms), then we may have to make the other profiles depend on the HTTP Baseline Profile.
