### ISSUE TITLE
Simplified array syntax

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#234]
The TD spec has multiple places where a type or an _array of <type>_ is permitted.

This does not add significant value and saves at best 2 characters in a TD, which can omit the  brackets [].

The profile could mandate using the array syntax. This is a purely syntactic simplification -
it improves TD readability, and (slightly) simplifies consumer implementation.

**Comment by benfrancis** [comment]
I disagree that this improves TD readability and I don't think that it's worth constraining. It's not complicated for a Consumer to support both an array and a string.

The terms that I can find which accept a string or array:
- `@type `
- `security`
- `scopes`
- `hreflang`
- `op`

For most of these it's probably more frequent that they have a single value vs. multiple values, so the array is usually unnecessary.

I don't understand why `oneOf` and `allOf` can be a string in [section 5.3.3.4](https://w3c.github.io/wot-thing-description/#combosecurityscheme) of WoT Thing Description, but that should be fixed in the TD spec (see https://github.com/w3c/wot-thing-description/issues/1595).

**Comment by mlagally** [comment]
I'm not convinced and don't agree that we should be mixing types if we can easily avoid it.
In the interest of getting the spec done however, I withdraw the issue.
