### ISSUE TITLE
Clarifying whether profiles are just a subset

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#243]
I have noted at https://github.com/w3c/wot-profile/pull/238#discussion_r918891099 that the document says that it is a subset of the TD. This is not true in my opinion. How the actions work is not just a subset of the TD, cannot be described in a TD. So it is more like that these profiles take the TD spec, restrict it and then add some small stuff on top.

**Comment by benfrancis** [comment]
This text is the definition of the HTTP Baseline Profile in section [3.1 Additional Definitions](https://w3c.github.io/wot-profile/#additional-definitions-).

> HTTP Baseline Profile
>    The subset of the Thing Description defined by the present document. 

I agree that's not a good definition of what the HTTP Baseline Profile is, since the "present document" describes multiple profiles, as well as the profile mechanism itself, and none of the profiles are just a subset of the Thing Description specification.

I don't think HTTP Baseline Profile actually needs a definition here, since it's a section heading naming an instance of a profile, not really a term that needs defining. The HTTP Baseline profile can be explained in its own introduction. We don't have definitions for "HTTP SSE Profile" or "HTTP Webhook Profile".

The current definition of "Profile" is a bit better, but could also do with some work.

Current text:

> Profile
> A set of prescriptive rules, to ensure that compliant implementations satisfy the semantic guarantees that are implied by them.

My suggestion:

"A technical specification which provides a set of assertions such that any Consumer which conforms with the those assertions is out-of-the-box interoperable with any Thing which also conforms with those assertions."

As we have established in [1.4 Out-of-the-box interoperability](https://w3c.github.io/wot-profile/#out-of-the-box-interoperability), semantic interoperability is only one layer of interoperability. The definition could link to that section.

**Comment by mlagally** [comment]
@benfrancis wrote:
> My suggestion:
> 
> "A technical specification which provides a set of assertions such that any Consumer which conforms with the those assertions is out-of-the-box interoperable with any Thing which also conforms with those assertions."
> 
> As we have established in [1.4 Out-of-the-box interoperability](https://w3c.github.io/wot-profile/#out-of-the-box-interoperability), semantic interoperability is only one layer of interoperability. The definition could link to that section.

I agree with the proposed language and support this change.
