### ISSUE TITLE
Removing HTTP Profile Specification mention

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#244]
As said in https://github.com/w3c/wot-profile/pull/238/files/36a15b9790aadc424756dda44ca9b8796ff088bc#r918891718 , any mention of HTTP Profile Specification should be changed to WoT Profile Specification

**Comment by benfrancis** [comment]
It looks like the term "HTTP Profile specification" only appears in that one instance.

Why is there even an "HTTP Profile" section? There is no HTTP Profile.

There are now three separate profiles which should be in their own top level sections:
1. HTTP Baseline Profile
2. HTTP SSE Profile
3. HTTP Webhook Profile

I think this could be fixed by just removing the HTTP Profile section heading and that following paragraph, see #214.

**Comment by mlagally** [comment]
Addressed in #247

**Comment by mlagally** [comment]
We now consistently use the term "HTTP Profile Specification" when we speak about the document.
The Term "HTTP Profiles" is used to refer to the 3 profiles the specification currently contains.
Suggest we close this issue.

**Comment by egekorkan** [comment]
> We now consistently use the term "HTTP Profile Specification" when we speak about the document. The Term "HTTP Profiles" is used to refer to the 3 profiles the specification currently contains. Suggest we close this issue.

Doing a search in the editor's draft of "http profile specification" results in 0 hits. So it is not exactly consistently used. The mention of HTTP Profiles is also happening first in section 1.3. I think that the issue cannot be closed until this is actually consistent.
