### ISSUE TITLE
Clarify the payload formats of read/write property

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#302]
Is the description in the TD sufficient to unambiguously know the format for read/write payloads?
Do we want to define a wrapper for the payload? Some examples would be useful.

**Comment by benfrancis** [comment]
> Is the description in the TD sufficient to unambiguously know the format for read/write payloads?

Yes, the payload maps directly onto the data schema provided in the property affordance. In the case of all the currently defined profiles this is serialised in JSON, the process for which is described in the TD specification. Meta operations use a map of property names to values.

> Do we want to define a wrapper for the payload? Some examples would be useful.

Definitely not, because this would unnecessarily break compatibility with non-comformant Consumers.
