### ISSUE TITLE
"Core" profile name has undesired implications

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-profile#5]
The name "core" of the profile may have undesired implications.

For me "core" is something that needs to be always supported/there. Just take as an example a library with a "core" part and some extensions. The core parts needs to be always present.

I don't believe this is the intent of the *core* profile.
Hence "constraint-limited-http-profile" or so might be better(see also #4)

**Comment by egekorkan** [comment]
I do agree on this and the figure 1 shows that this implication is actually desired

**Comment by mlagally** [comment]
Proposal: "classic", "base"

**Comment by benfrancis** [comment]
> For me "core" is something that needs to be always supported/there.

This is exactly what I think this core profile should be, a default protocol binding that all web things should support if they want to enable ad-hoc interoperability. "base" also works.

**Comment by egekorkan** [comment]
> all web things should support

I think this would imply big contradictions to how the standardization effort has started in the beginning and what it tries to achieve. The idea was being able to simply to describe something that already exists and to show that we can achieve interoperability this way. If we say that some technology SHOULD be supported by WoT implementations, we divert greatly from this point of view and we impose something on implementors. Of course, we can say that "you are not ad-hoc interoperable, you have profile X and a consumer thing would need profile X as well". However, this would encourage the siloes once again and destroy the cross-domain interoperability vision.

As what @danielpeintner said, the "core" profile is in the end "constraint-limited-http-profile". Using a word like **base** or **core**, implies that everyThing should support this profile. **Classic** sounds old on the other hand, like the way we are used to doing things.

I still believe that what we want to achieve with core profile can be achieved with a specific implementation guide which ensures that the TDs produced by following this guide are easy to understand and are ad-hoc interoperable with many clients available.

**Comment by draggett** [comment]
I agree with the aim for supporting existing IoT ecosystems, but also believe that there is a need to encourage convergence on a Web standard for connecting suppliers and services across the Internet. Would the Web have been so successful if different companies used different protocols?

**Comment by benfrancis** [comment]
@egekorkan I can accept that developers might want to write Thing Descriptions to describe existing brownfield devices which use web protocols in a different way to that defined in the core profile.

What I said was "all web things should support **if they want to enable ad-hoc interoperability**".

> I think this would imply big contradictions to how the standardization effort has started in the beginning and what it tries to achieve. The idea was being able to simply to describe something that already exists and to show that we can achieve interoperability this way. If we say that some technology SHOULD be supported by WoT implementations, we divert greatly from this point of view and we impose something on implementors. Of course, we can say that "you are not ad-hoc interoperable, you have profile X and a consumer thing would need profile X as well". However, this would encourage the siloes once again and destroy the cross-domain interoperability vision.

I really think this is the wrong way around. If all you do is describe what already exists then you are ensuring that silos continue to exist because not all WoT clients can communicate with all WoT devices. Ad-hoc interoperability between WoT clients and WoT servers requires that they all speak a common protocol.

Defining a core profile, or rather a default protocol binding, enables ad-hoc interoperability.

**Comment by egekorkan** [comment]
> a default protocol binding, enables ad-hoc interoperability. 

I totally agree with this. However, this document seems to aim more than that. We can talk further on this in a CG like you said in https://github.com/w3c/wot-profile/issues/2#issuecomment-527180187 or in WoT Protocol Binding Templates

**Comment by benfrancis** [comment]
> I totally agree with this. However, this document seems to aim more than that. We can talk further on this in a CG like you said in #2 (comment) or in WoT Protocol Binding Templates

Alternatively this document could evolve into a "WoT HTTP Protocol Binding" instead of "WoT Profiles".

Although I support this Core Profile effort as a means to define a default HTTP protocol binding for the Web of Things, I am bit concerned that in response to a call for simplification, the Working Group has come up with a profile mechanism which instead fact adds _further_ complexity and risks further fragmentation through the definition of vertical profiles.

A simpler approach would simply to use this specification to define a more complete HTTP protocol binding than is currently defined in the TD spec and provide a mechanism to refer to the protocol binding specification from a Thing Description using a URI, as suggested by @draggett in https://github.com/w3c/wot-profile/issues/2#issuecomment-527175118.

**Comment by benfrancis** [comment]
We need to reach a consensus on this. My suggestion in #21 was to call it the "Common Profile", but I am also OK with "HTTP & JSON Profile" or sticking with "Core Profile".

**Comment by benfrancis** [comment]
See also comments in #25

**Comment by benfrancis** [comment]
Another suggestion from https://github.com/w3c/wot-profile/issues/152#issuecomment-988754123...

What if we called the current profile something like the "**HTTP+JSON Thing Server**" profile?

That would allow for future profiles like:
- "**CoAP+CBOR Thing Server**" profile - For constrained things
- "**HTTP+JSON Directory Server**" profile Directories/gateways which offer additional features (e.g. a [directory API](https://w3c.github.io/wot-discovery/#directory-api-spec) and listening to multiple things over a single connection)
- "**HTTP+JSON Thing Client**" profile - Things which act as HTTP clients (e.g. a sensor sending readings to a cloud service) and Consumers which act as HTTP servers (e.g. a cloud service which listens for connections from Things), where a Thing/Consumer can optionally implement both this and the first profile (see the discussion in #152 for the rationale)

**Comment by benfrancis** [comment]
> What I am unsure with is the differentiation between "server" and "client" thinking ... shouldn't there be "a" profile which in the end allows server & client to communicate?

Yes, but please see the linked discussion in #152. @mlagally would like to support an alternative deployment model where Things are clients and Consumers are servers, hence "Thing Client" vs. "Thing Server". Both models involve a client and a server but they work in different directions. Perhaps there's alternative wording that would make that clearer because I agree it's confusing.

**Comment by benfrancis** [comment]
In #152, @mmccool said:
> For the name, I propose "HTTP/JSON Profile" and we drop all "common" or "core" terms.

+1 for "HTTP+JSON Profile". I would be happy with that.

**Comment by sebastiankb** [comment]
+1 for HTTP Baseline Profile

**Comment by mlagally** [comment]
resolution: use the name "HTTP Baseline Profile" for the HTTP profile that includes properties and actions.
