### ISSUE TITLE
Max number of objects

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#67]
The maximum number of properties, actions and nested structures should be defined.
This will help to limit implementation complexity of UIs.

If a higher number of elements is needed, it is always possible to break down complex 
things into compositions of smaller building blocks.

**Comment by mlagally** [comment]
Arch call on 28.1.:
Plugfest:
Rarely we see more than 10 properties and actions
Range is ~10-30 per interaction affordance type
Automatically generated TDs could be bigger

A typical Zigbee cluster has 20-30 affordances
Some devices may have 100
Modbus devices have 128 registers
Limit of 200-300 would make sense

250?
1000

We should pick a reference device:
e.g. Arm Cortex M0 - 16k RAM
ATMEL 2k / 8k RAM, 32k flash up to 2Mb

Guesstimate:

8 bytes for name, 8 bytes for value
-> 2048/(8+8) = 128 elements

**Comment by sebastiankb** [comment]
We should never prescribe such a constraint. Gateways or edge devices may offer over 1000 properties. Some UI have already trouble to display 30 properties, other client implementations can handle 1000 properties easily. We should not intervene in such matters and leave it up to the market.

**Comment by mjkoster** [comment]
This is the 2 channel DIN-rail PID controller example I am adapting. It is a dual PID controller, each channel having 2 analog inputs, 1 analog output, 1 discrete input, and 1 discrete output.

http://www.rts.ua/catalog/advantech/pdf/ADAM-4022T_2_201316.pdf

The device has 19 operational registers (8 per controller + 3 device ID) and 4 coils which expose the SCADA/DCS relevant values from both controllers (23 Properties)
In addition, each PID controller has 48  configuration registers (96 Properties)

48 + 48 (config reg) + 19 (op reg) + 4 (coil) = 119 Properties total

If we split it up, it makes sense to make TDs for

PID 0 configuration - 48 Properties
PID 1 configuration - 48 Properties
Device control - 23 Properties (also may be split into 2 separate TDs) also may define Events for the alarms and Actions for changing Setpoints

Here are the SDF definitions I made for this device, one for the operational part and one for the configuration part.
https://github.com/mjkoster/onefb-sdk/blob/main/control-models/modbus/sdfthing-modbus-multicontroller.sdf.json
https://github.com/mjkoster/onefb-sdk/blob/main/control-models/modbus/sdfobject-modbus-pid-parameters.sdf.json

**Comment by mlagally** [comment]
@sebastiankb @benfrancis 
Think of consuming a TD for another device on a very resource constrained device and displaying a UI.
You have to:
- read the TD
- process it
- allocate UI elements (which consume RAM)
- display them on a typically rather limited screen
- provide navigation
- handle input
- control the device

We had a discussion about a reference device and were considering devices with a few KB (1-64K) of RAM.
See for example:  https://en.wikipedia.org/wiki/AVR_microcontrollers

**Comment by egekorkan** [comment]
I second the comment of @benfrancis at https://github.com/w3c/wot-profile/issues/66 which says 

> This is another example of a constraint which is important for constrained devices but could unnecessarily harm human readability for a less constrained device

I think that this constraint cannot be applied in the core profile but for a constrained device profile. The discussions in the call were about how many interactions per resource can be stored in the ram of a device. However, this is misleading since there are other things that will use the RAM that we have nothing to say about. Furthermore, I think that a constraint on amount of interactions set for a UI would be different than ones set for a constraint device hosting a TD and its server-side handlers. 

We can however say something like 10 interactions (less than what is discussed) and _hopefully_ that can give a guarantee to work on constraint devices and UIs most of the time. Trying to display more than 10 (maybe 20) visual elements on a non-scrollable 14 inch screen already seems difficult to me. 

In any case, I think that we need concrete examples of Thing implementations on constrained devices before proceeding. I can provide examples for ESP 8266 or 32 but these have more resources than the above mentioned devices

**Comment by sebastiankb** [comment]
@mlagally 
>We had a discussion about a reference device and were considering devices with a few KB (1-64K) of RAM.
See for example: https://en.wikipedia.org/wiki/AVR_microcontrollers

Well the mentioned uC would be already overwhelmed when a [simple TD](https://www.w3.org/TR/wot-thing-description/#simple-thing-description-sample) is exchanged via HTTP/TCP. At that kind of level you will never work with plain-text representation and text-based communication protocols. All this discussion should be considered in the constrained profile. Also see https://github.com/w3c/wot-thing-description/issues/2

**Comment by mlagally** [comment]
@sebastiankb 
thanks, we are getting closer on seeing the real problem.
Do you have a suggested reference device for the smallest kind of embedded device a TD will be suitable for?

**Comment by sebastiankb** [comment]
@mlagally 
>Do you have a suggested reference device for the smallest kind of embedded device a (text based) TD will be suitable for?ü

There is no clear answer for this since this depends on the use case. If we are serious, we need to look at the whole package: firmware / OS, secure data exchange, TCP/HTTP(S)/JSON stack and the actual device application. The IoT hardware landscape is huge and have to beselected based on the specific requirement.

**Comment by benfrancis** [comment]
There seems to be a consensus that there should be no arbitrary limit on the number or properties/actions/events. I propose closing.
