### ISSUE TITLE
Collect Use Cases and Scenarios for Profiles

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-profile#71]
To better understand when and where a profile is applicable, and when constraints (e.g. on TD size) or other requirements beyond the core specs (e.g TD) are needed, we need realistic use cases (ideally tied to actual products, or at least what is expected on the markets, what protocols and price points are likely to be, and so forth).

Please add use cases etc. here; please limit it to use cases for *profiles* since general use cases should of course go into the use cases document.

The ultimate outcome should be a clearer understanding and consensus on the purpose of profiles and where and when they are useful.

**Comment by benfrancis** [comment]
I'd like to share the [use cases and requirements](https://w3c.github.io/web-thing-protocol/requirements) collected by the [Web Thing Protocol Community Group](https://www.w3.org/community/web-thing-protocol/) which I think are relevant here.

The current draft report lists use cases for [WoT Clients](https://w3c.github.io/web-thing-protocol/requirements/#wot-clients), [WoT Devices](https://w3c.github.io/web-thing-protocol/requirements/#wot-devices) and [WoT Gateways & Directories](https://w3c.github.io/web-thing-protocol/requirements/#wot-gateways-directories).

Of particular relevance is the list of [requirements for an HTTP sub-protocol](https://w3c.github.io/web-thing-protocol/requirements/#http-sub-protocol) which I suggest could form the basis of a WoT Core Profile that:
1. Requires that all conformant WoT consumers and WoT producers support HTTP & JSON
2. Provides a concrete protocol binding/sub-protocol which defines how to communicate with devices including requests and responses expected for any given operation and their methods, headers, payloads and expected response codes

In terms of products which have these requirements, from my own experience I can point to:
- [WebThings Gateway](https://webthings.io/gateway/) - A WoT Gateway (producer & consumer) application which can run on anything from a $35 Raspberry Pi 3 to $1k+ industrial IoT gateways and cloud servers
- [WebThings Framework](https://webthings.io/framework/) - WoT server (producer) implementations in a dozen different programming languages which can run on anything from a $4 Raspberry Pi Pico microcontroller running MicroPython or $10 Arduino ESP32 developer board up to powerful industrial IoT devices with multi-core ARM/x86/x86-64/IA64/AMD64 microprocessors
- [Krellian Kiosk](https://github.com/krellian/kiosk) - Software for digital signage displays which act as WoT devices (producers) which can run on anything from a $35 Raspberry Pi 3 or $1k Intel NUC rugged industrial PC to $10k+ commercial NEC digital signage displays with a built-in compute module
- WebThings App - An in-development native mobile app which acts as a general purpose WoT client (consumer) running on Android & iOS smartphones and tablets ($10-$1k)

**Comment by sebastiankb** [comment]
I think to identify the use cases, it makes sense what typical roles we have in the IoT. So far, I miss a clear separation between a consumer and a producer in the discussions. 

Sensors and actuators typically act as producers and a profile should have the power to describe any type of such device, even if it only offers 2 data points or 200 different data points / functions as well as being a device with a few kB RAM or GB RAM. I already shared an example of an automation device [here](https://github.com/w3c/wot-profile/pull/69#discussion_r578584893). Device manufacturers will always implement the desired device capabilities and not care if there is a device description that would potential affect the capability due to a generic size limitations.

My impression is that the discussion is mainly about a consumer who should be able to consume any kind of profile-based TD. What for classical consumer do we have in our PlugFest? Mainly, I see generic approaches such as W-ADE, node-red and node-wot. How about consumers for resource constrained devices? Is there also an expectation that any kind of profile-based TD should be understood? I don't think so. The consumers there are implemented in such a way that they expect TDs with certain characteristics, e.g. that a certain semantics and information model is used, otherwise it is not able to do anything with its content.  E.g., consumers that follow LwM2M will expect TDs that reflects LwM2M. The implementation of such consumer will follow more the expected capability of LwM2M which may also in a conflict with a generic size limitation of a TD. 

I think there are reasons why approaches like Vorto and DTDL do not have such a generic constraint. My suggestion is that a profile that mainly uses HTTP(S)/JSON should not have TD size constraints. It would be strange if more powerful systems like Edge / Hub / Cloud had to split TDs of an IoT system due to a generic size limitation. This would complicate everything once again.

**Comment by egekorkan** [comment]
I second the comment above. Unless we start seeing some resource-constrained Consumers in our Plugfests, I don't think that we have the knowledge to define such restrictions. Maybe @Citrullin can provide such Consumers but he was concentrating on a CoAP stack already and thus not applicable to an HTTP profile.

**Comment by mlagally** [comment]
Arch call on 11.3.
We should think about the 3 different entities in our architecture, but can start with thing and consumer for now.

What would happen if we don't have a size limit:

Some devices would be too small to consume some TDs that are huge, e.g. exceeding the RAM on that device. 
-> The device would not be interoperable with the producer of the large TD

Sensor data can be still processed in a stream, however a TD needs to be read and validated before usage.

**Comment by mlagally** [comment]
A set of use cases has been published in [the](https://www.w3.org/TR/wot-usecases/).
New requirements for Profile 2.0 should be discussed in the use cases TF first, before they are passed on to the Profile TF.
